"""Initial migration - create all tables

Revision ID: d30d06f8c4ac
Revises: 
Create Date: 2026-01-13 22:56:49.199381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd30d06f8c4ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preset_opt_runs_mode_created'), table_name='preset_optimization_runs')
    op.drop_index(op.f('ix_preset_opt_runs_status'), table_name='preset_optimization_runs')
    op.drop_index(op.f('ix_preset_optimization_runs_created_at'), table_name='preset_optimization_runs')
    op.drop_index(op.f('ix_preset_optimization_runs_run_id'), table_name='preset_optimization_runs')
    op.drop_table('preset_optimization_runs')
    op.drop_index(op.f('idx_trg_active'), table_name='trg_presets')
    op.drop_index(op.f('idx_trg_category'), table_name='trg_presets')
    op.drop_index(op.f('idx_trg_name'), table_name='trg_presets')
    op.drop_index(op.f('idx_trg_source'), table_name='trg_presets')
    op.drop_table('trg_presets')
    op.drop_index(op.f('idx_dp_active'), table_name='dominant_presets')
    op.drop_index(op.f('idx_dp_category'), table_name='dominant_presets')
    op.drop_index(op.f('idx_dp_indicator'), table_name='dominant_presets')
    op.drop_index(op.f('idx_dp_source'), table_name='dominant_presets')
    op.drop_index(op.f('idx_dp_symbol'), table_name='dominant_presets')
    op.drop_table('dominant_presets')
    op.add_column('presets', sa.Column('settings', sa.JSON(), nullable=False))
    op.add_column('presets', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('presets', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.alter_column('presets', 'id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('presets', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('presets', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('presets', 'indicator_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'trg'"))
    op.alter_column('presets', 'is_favorite',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('presets', 'tags',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('presets', 'win_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('presets', 'profit_factor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('presets', 'total_profit_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('presets', 'max_drawdown_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('presets', 'sharpe_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('presets', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('presets', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index(op.f('idx_p_active'), table_name='presets')
    op.drop_index(op.f('idx_p_category'), table_name='presets')
    op.drop_index(op.f('idx_p_indicator'), table_name='presets')
    op.drop_index(op.f('idx_p_name'), table_name='presets')
    op.drop_index(op.f('idx_p_source'), table_name='presets')
    op.drop_index(op.f('idx_p_symbol'), table_name='presets')
    op.create_index(op.f('ix_presets_name'), 'presets', ['name'], unique=False)
    op.drop_column('presets', 'timeframe')
    op.drop_column('presets', 'is_active')
    op.drop_column('presets', 'avg_trade_percent')
    op.drop_column('presets', 'total_trades')
    op.drop_column('presets', 'symbol')
    op.drop_column('presets', 'universality_score')
    op.drop_column('presets', 'params')
    op.drop_column('presets', 'category')
    op.drop_column('presets', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presets', sa.Column('source', sa.TEXT(), server_default=sa.text("'manual'"), nullable=True))
    op.add_column('presets', sa.Column('category', sa.TEXT(), server_default=sa.text("'mid-term'"), nullable=False))
    op.add_column('presets', sa.Column('params', sa.TEXT(), nullable=False))
    op.add_column('presets', sa.Column('universality_score', sa.REAL(), nullable=True))
    op.add_column('presets', sa.Column('symbol', sa.TEXT(), nullable=True))
    op.add_column('presets', sa.Column('total_trades', sa.INTEGER(), nullable=True))
    op.add_column('presets', sa.Column('avg_trade_percent', sa.REAL(), nullable=True))
    op.add_column('presets', sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
    op.add_column('presets', sa.Column('timeframe', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_presets_name'), table_name='presets')
    op.create_index(op.f('idx_p_symbol'), 'presets', ['symbol'], unique=False)
    op.create_index(op.f('idx_p_source'), 'presets', ['source'], unique=False)
    op.create_index(op.f('idx_p_name'), 'presets', ['name'], unique=False)
    op.create_index(op.f('idx_p_indicator'), 'presets', ['indicator_type'], unique=False)
    op.create_index(op.f('idx_p_category'), 'presets', ['category'], unique=False)
    op.create_index(op.f('idx_p_active'), 'presets', ['is_active'], unique=False)
    op.alter_column('presets', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('presets', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('presets', 'sharpe_ratio',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('presets', 'max_drawdown_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('presets', 'total_profit_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('presets', 'profit_factor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('presets', 'win_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('presets', 'tags',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('presets', 'is_favorite',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('presets', 'indicator_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'trg'"))
    op.alter_column('presets', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('presets', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('presets', 'id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)
    op.drop_column('presets', 'last_used_at')
    op.drop_column('presets', 'is_default')
    op.drop_column('presets', 'settings')
    op.create_table('dominant_presets',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('indicator_type', sa.TEXT(), server_default=sa.text("'dominant'"), nullable=False),
    sa.Column('category', sa.TEXT(), server_default=sa.text("'mid-term'"), nullable=False),
    sa.Column('symbol', sa.TEXT(), nullable=True),
    sa.Column('timeframe', sa.TEXT(), nullable=True),
    sa.Column('params', sqlite.JSON(), nullable=False),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'manual'"), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('is_favorite', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('win_rate', sa.REAL(), nullable=True),
    sa.Column('profit_factor', sa.REAL(), nullable=True),
    sa.Column('total_profit_percent', sa.REAL(), nullable=True),
    sa.Column('max_drawdown_percent', sa.REAL(), nullable=True),
    sa.Column('sharpe_ratio', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_dp_symbol'), 'dominant_presets', ['symbol'], unique=False)
    op.create_index(op.f('idx_dp_source'), 'dominant_presets', ['source'], unique=False)
    op.create_index(op.f('idx_dp_indicator'), 'dominant_presets', ['indicator_type'], unique=False)
    op.create_index(op.f('idx_dp_category'), 'dominant_presets', ['category'], unique=False)
    op.create_index(op.f('idx_dp_active'), 'dominant_presets', ['is_active'], unique=False)
    op.create_table('trg_presets',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), server_default=sa.text("'mid-term'"), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=False),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'system'"), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('is_favorite', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('win_rate', sa.REAL(), nullable=True),
    sa.Column('profit_factor', sa.REAL(), nullable=True),
    sa.Column('total_profit_percent', sa.REAL(), nullable=True),
    sa.Column('max_drawdown_percent', sa.REAL(), nullable=True),
    sa.Column('sharpe_ratio', sa.REAL(), nullable=True),
    sa.Column('total_trades', sa.INTEGER(), nullable=True),
    sa.Column('avg_trade_percent', sa.REAL(), nullable=True),
    sa.Column('universality_score', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('idx_trg_source'), 'trg_presets', ['source'], unique=False)
    op.create_index(op.f('idx_trg_name'), 'trg_presets', ['name'], unique=False)
    op.create_index(op.f('idx_trg_category'), 'trg_presets', ['category'], unique=False)
    op.create_index(op.f('idx_trg_active'), 'trg_presets', ['is_active'], unique=False)
    op.create_table('preset_optimization_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mode', sa.VARCHAR(length=20), nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('original_preset_count', sa.INTEGER(), nullable=True),
    sa.Column('original_pair_count', sa.INTEGER(), nullable=True),
    sa.Column('effective_preset_count', sa.INTEGER(), nullable=True),
    sa.Column('effective_pair_count', sa.INTEGER(), nullable=True),
    sa.Column('preset_ids', sqlite.JSON(), nullable=True),
    sa.Column('pairs', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('total_combinations', sa.INTEGER(), nullable=True),
    sa.Column('completed_combinations', sa.INTEGER(), nullable=True),
    sa.Column('num_workers', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('best_preset_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('best_preset_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('best_overall_score', sa.FLOAT(), nullable=True),
    sa.Column('best_avg_pnl', sa.FLOAT(), nullable=True),
    sa.Column('top_10_presets', sqlite.JSON(), nullable=True),
    sa.Column('result_matrix', sqlite.JSON(), nullable=True),
    sa.Column('preset_scores', sqlite.JSON(), nullable=True),
    sa.Column('errors', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preset_optimization_runs_run_id'), 'preset_optimization_runs', ['run_id'], unique=1)
    op.create_index(op.f('ix_preset_optimization_runs_created_at'), 'preset_optimization_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_preset_opt_runs_status'), 'preset_optimization_runs', ['status'], unique=False)
    op.create_index(op.f('ix_preset_opt_runs_mode_created'), 'preset_optimization_runs', ['mode', 'created_at'], unique=False)
    # ### end Alembic commands ###
